--- #Delimits each Cloud Environment
datacenters:
  - !datacenter
    name: datacenter1
    amount: 1
    vmAllocationPolicy: Simple
    architecture: x86
    os: Linux
    vmm: Xen
    upperUtilizationThreshold: 0.8
    lowerUtilizationThreshold: 0.2
    vmMigration: enabled
    schedulingInterval: 30
    monitoringInterval: 180
    costPerSec: 0.1
    costPerMem: 0.05
    costPerStorage: 0.001
    costPerBw: 0.1
    sans:
      - !san
        name: san1
        capacity: 10000
        bandwidth: 10000
        networkLatency: 5
      - !san
        name:
        capacity: 50000
        bandwidth: 20000
        networkLatency: 5
    hosts:
      - !host
        id: 1
        amount: 10
        ram: 80000
        bw: 50000
        storage: 500000
        maxPower: 250
        staticPowerPercent: 0.7
        pes: 4
        mips: 100000
        vmScheduler: TimeShared
        powerModel: Linear
        ramProvisioner: Simple
        bwProvisioner: Simple
        peProvisioner: Simple
      - !host
        amount: 4
        ram: 1000000
        bw: 80000
        storage: 40000
        maxPower: 250
        staticPowerPercent: 0.7
        pes: 4
        mips: 50000
        vmScheduler: TimeShared
        powerModel: Linear
        ramProvisioner: Simple
        bwProvisioner: Simple
        peProvisioner: Simple
  - !datacenter
    name: 
    amount: 2
    vmAllocationPolicy: Simple
    architecture: x86
    os: Linux
    vmm: Xen
    upperUtilizationThreshold: 0.8
    lowerUtilizationThreshold: 0.2
    vmMigration: enabled
    schedulingInterval: 30
    monitoringInterval: 180
    costPerSec: 0.1
    costPerMem: 0.05
    costPerStorage: 0.001
    costPerBw: 0.1
    sans:
      - !san
        name: san1
        capacity: 10000
        bandwidth: 10000
        networkLatency: 5
      - !san
        name:
        capacity: 50000
        bandwidth: 20000
        networkLatency: 5
    hosts:
      - !host
        id: 1
        amount: 10
        ram: 500000
        bw: 40000
        storage: 1000000
        maxPower: 250
        staticPowerPercent: 0.7
        pes: 4
        mips: 200000
        vmScheduler: TimeShared
        powerModel: Linear
        ramProvisioner: Simple
        bwProvisioner: Simple
        peProvisioner: Simple
      - !host
        amount: 4
        ram: 2000000
        bw: 120000
        storage: 850000
        maxPower: 250
        staticPowerPercent: 0.7
        pes: 4
        mips: 400000
        vmScheduler: TimeShared
        powerModel: Linear
        ramProvisioner: Simple
        bwProvisioner: Simple
        peProvisioner: Simple
customers:
  - !customer
    name: Customer1
    amount: 1
    vms:
      - !vm
        amount: 10
        size: 500
        pes: 2
        mips: 1000
        ram: 2000
        bw: 100
        priority: 1
        vmm: Xen
        cloudletScheduler: TimeShared
      - !vm
        amount: 8
        size: 400
        pes: 4
        mips: 1000
        ram: 1400
        bw: 80
        priority: 1
        vmm: Xen
        cloudletScheduler: TimeShared
    cloudlets:
      - !cloudlet
        amount: 5
        pes: 2
        length: 100
        fileSize: 50
        outputSize: 50
        utilizationModelCpu: Full
        utilizationModelRam: Full
        utilizationModelBw: Full
      - !cloudlet
        amount: 15
        pes: 1
        length: 150
        fileSize: 50
        outputSize: 50
        utilizationModelCpu: Full
        utilizationModelRam: Full
        utilizationModelBw: Full
  - !customer
    name:
    amount: 2
    vms:
      - !vm
        amount: 10
        size: 1000
        pes: 2
        mips: 1000
        ram: 1000
        bw: 250
        priority: 1
        vmm: Xen
        cloudletScheduler: TimeShared
      - !vm
        amount: 8
        size: 1000
        pes: 4
        mips: 1000
        ram: 2000
        bw: 180
        priority: 1
        vmm: Xen
        cloudletScheduler: TimeShared
    cloudlets:
      - !cloudlet
        amount: 5
        pes: 2
        length: 1000
        fileSize: 80
        outputSize: 80
        utilizationModelCpu: Full
        utilizationModelRam: Full
        utilizationModelBw: Full
      - !cloudlet
        pes: 1
        length: 1000
        fileSize: 30
        outputSize: 30
        utilizationModelCpu: Full
        utilizationModelRam: Full
        utilizationModelBw: Full
         
      